image: registry.windmaker.net:5005/a-castellano/limani/base_hugo:latest

stages:
    - build
    - deploy

build:
  stage: build
  script:
    - hugo

deploy:
  stage: deploy
  before_script:
    - echo "test"
  script:
    - ls -lahrt public
  dependencies:
  - build

