image: registry.windmaker.net:5005/a-castellano/limani/base_hugo:latest

stages:
    - build
    - deploy

build:
  stage: build
  script:
    - hugo
  artifacts:
    name: "build-$CI_PIPELINE_ID"
    paths:
      - public
    expire_in: 10 minutes

deploy:
  stage: deploy
  before_script:
    - echo "test"
  script:
    - ls -lahrt public
  dependencies:
  - build

