image: registry.windmaker.net:5005/a-castellano/limani/base_hugo:202408211952

stages:
    - build
    - deploy

build:
  stage: build
  script:
    - hugo
    - mv public release
  artifacts:
    name: "build-$CI_PIPELINE_ID"
    paths:
      - release
    expire_in: 10 minutes

deploy:
  stage: deploy
  before_script:
    - ssh -vv -i ${PRIVATE_SSH_KEY} ${SSH_USER}@${SSH_HOST} ls -lahrt
  script:
    - rsync -e "ssh -i $(pwd)/.ssh/id_rsa" -e "ssh -o StrictHostKeyChecking=no" -a --delete release/ ${SSH_USER}@${SSH_HOST}:${DOC_ROOT}/
  dependencies:
  - build

