image: registry.windmaker.net:5005/a-castellano/limani/base_hugo:202408211952

stages:
    - deploy

deploy:
  stage: deploy
  before_script:
    - chmod 400 ${PRIVATE_SSH_KEY}
    - ssh -vv -i ${PRIVATE_SSH_KEY} -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} ls -lahrt
  script:
    - hugo
    - mv public release
    - rsync -e "ssh -i \"${PRIVATE_SSH_KEY}\" -o StrictHostKeyChecking=no -o PubKeyAcceptedAlgorithms=+ssh-rsa" -a --delete release/ ${SSH_USER}@${SSH_HOST}:${DOC_ROOT}/
